name: JavaScript

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "javascriptv3/**/*.{js,ts,jsx,tsx}"
      - name: Setup NodeJS
        if: steps.changed-files.outputs.test_any_changed == 'true'  
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm i --prefix javascriptv3
        if: steps.changed-files.outputs.test_any_changed == 'true'  
      - name: Lint added and modified files
        if: steps.changed-files.outputs.test_any_changed == 'true'  
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          npm run --prefix javascriptv3 ci-lint -- ${changed_files[@]//javascriptv3\/}
