name: JavaScript

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "javascriptv3/**/*.{js,ts,jsx,tsx}"
      - name: Test Output
        run: |
            for file in ${{steps.changed-files.outputs.all_changed_files}}; do
              echo "$file was changed"
            done
      - name: Setup NodeJS
        if: ${{steps.changed-files.outputs.all_changed_files}} > 0  
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        if: ${{steps.changed-files.outputs.all_changed_files[0]}} != null  
        run: npm i --prefix javascriptv3
      - name: Lint added and modified files
        if: ${{steps.changed-files.outputs.all_changed_files}} == 'true'  
        run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          npm run --prefix javascriptv3 ci-lint -- ${changed_files[@]//javascriptv3\/}
