name: JavaScript

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    name: Changed Files Detection
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      javascript: ${{ steps.filter.outputs.javascript }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          javascript:
            - "javascriptv3/**"
  lint:
    name: Lint Javascript
    needs: changes
    if: ${{ needs.changes.outputs.javascript == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "javascriptv3/**/*.{js,ts,jsx,tsx}"
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm i --prefix javascriptv3
        name: Install dependencies
      - run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          npm run --prefix javascriptv3 ci-lint -- ${changed_files[@]//javascriptv3\/}
        name: Lint added and modified files
