name: ktlint

on:
  pull_request:
    paths:
      - .github/workflows/kotlin-lint.yml
      - 'kotlin/**/*.{kt,kts}'

jobs:
  ktlint:
    name: Lint Kotlin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            .github
            kotlin
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "kotlin/**/*.{kt,kts}"
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      - name: Install ktlint via curl
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: Run ktlint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ktlint --reporter=plain?group_by_file
        continue-on-error: false
      - name: Report on ktlint
        uses: yutailang0119/action-ktlint@v4
        with:
          report-path: build/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
          ignore-warnings: true # Ignore Lint Warnings
        continue-on-error: false # If annotations contain error of severity, action-ktlint exit 1.
